[project]
name = "comfyui-mnemic-nodes"
description = "Updated a bunch of inputs and outputs of the Save Text File With Path-node. This will break all existing workflows as almost all inputs have been redesigned."
version = "1.1.0"
license = "LICENSE"
dependencies = ["configparser", "groq", "transformers", "torch"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
