[project]
name = "comfyui-mnemic-nodes"
description = "Updated a bunch of inputs and outputs of the node for safety reasons and improvements. Will likely break workflows."
version = "1.0.3"
license = "LICENSE"
dependencies = ["﻿configparser", "groq", "transformers", "torch"]

[project.urls]
Repository = "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "mnemic"
DisplayName = "ComfyUI-mnemic-nodes"
Icon = ""
